## These functions create a special "matrix" object and set of functions to 
## calculate and cache the inverse of that matrix.

## `makeCacheMatrix` generates a matrix and a list of functions to get/set 
## that matrix and cache its own inverse. The provided matrix must be invertible

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinverse <- function(inverse) inv <<- inverse
    getinverse <- function() inv
    list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## `cacheSolve` computes and caches the inverse of the special "matrix" object 
## generated by `makeCacheMatrix`. If the inverse is already cached, it returns 
## the cached value

cacheSolve <- function(x, ...) {
    inv <- x$getinverse()
    if (!is.null(inv)){
        message("getting cached data")
        return(inv)
    } 
    data <- x$get()
    inv <- solve(data, ...)
    x$setinverse(inv)
    inv
}